import request from './request'

export const login = (data) => request.post('/user/login', data)
export const listUsers = () => request.get('/user/list')
export const listUsersByRole = (role) => request.get('/user/listByRole', { params: { role } })
export const getUser = (id) => request.get(`/user/${id}`)

export const listRooms = () => request.get('/room/list')
export const listRoomsByStatus = (status) => request.get(`/room/status/${status}`)
export const getRoom = (id) => request.get(`/room/${id}`)
export const createRoom = (data) => request.post('/room', data)
export const updateRoom = (data) => request.put('/room', data)
export const deleteRoom = (id) => request.delete(`/room/${id}`)

export const listLinenTypes = () => request.get('/linenType/list')
export const getLinenType = (id) => request.get(`/linenType/${id}`)
export const createLinenType = (data) => request.post('/linenType', data)
export const updateLinenType = (data) => request.put('/linenType', data)
export const deleteLinenType = (id) => request.delete(`/linenType/${id}`)

export const listCheckoutRecords = () => request.get('/checkoutRecord/list')
export const listCheckoutByRoom = (roomId) => request.get('/checkoutRecord/listByRoom', { params: { roomId } })
export const listCheckoutByCleaner = (cleanerId) => request.get('/checkoutRecord/listByCleaner', { params: { cleanerId } })
export const createCheckout = (data) => request.post('/checkoutRecord', data)
export const getCheckout = (id) => request.get(`/checkoutRecord/${id}`)

export const listLinenBags = (params) => request.get('/linenBag/list', { params })
export const getLinenBag = (id) => request.get(`/linenBag/${id}`)
export const getLinenBagByCode = (bagCode) => request.get(`/linenBag/bagCode/${bagCode}`)
export const listLinenBagsByCheckout = (checkoutId) => request.get(`/linenBag/checkout/${checkoutId}`)
export const listLinenBagsByStatus = (status) => request.get('/linenBag/listByStatus', { params: { status } })
export const createLinenBag = (data) => request.post('/linenBag', data)
export const updateLinenBagStatus = (id, status) => request.put(`/linenBag/${id}/status`, { status })
export const pickupLinenBag = (id, data) => request.put(`/linenBag/${id}/pickup`, data)
export const factoryCheckLinenBag = (id, data) => request.put(`/linenBag/${id}/factoryCheck`, data)
export const returnFromFactory = (id, data) => request.put(`/linenBag/${id}/returnFromFactory`, data)
export const warehouseCheckLinenBag = (id, data) => request.put(`/linenBag/${id}/warehouseCheck`, data)

export const listWashBatches = () => request.get('/washBatch/list')
export const getWashBatch = (id) => request.get(`/washBatch/${id}`)
export const getWashBatchByNo = (batchNo) => request.get(`/washBatch/batchNo/${batchNo}`)
export const listWashBatchesByStatus = (status) => request.get('/washBatch/listByStatus', { params: { status } })
export const createWashBatch = (data) => request.post('/washBatch', data)
export const addBagsToBatch = (batchId, bagIds) => request.post(`/washBatch/${batchId}/addBags`, bagIds)
export const startWashBatch = (id) => request.put(`/washBatch/${id}/start`)
export const finishWashBatch = (id, data) => request.put(`/washBatch/${id}/finish`, data)

export const listDeliveryReceipts = () => request.get('/deliveryReceipt/list')
export const listDeliveryByStatus = (status) => request.get('/deliveryReceipt/listByStatus', { params: { status } })
export const createDelivery = (data) => request.post('/deliveryReceipt', data)
export const deliverReceipt = (id) => request.put(`/deliveryReceipt/${id}/deliver`)
export const receiveReceipt = (id, data) => request.put(`/deliveryReceipt/${id}/receive`, data)
export const getDelivery = (id) => request.get(`/deliveryReceipt/${id}`)

export const listDamageReports = () => request.get('/damageReport/list')
export const listDamageByStatus = (status) => request.get('/damageReport/listByStatus', { params: { status } })
export const createDamageReport = (data) => request.post('/damageReport', data)
export const approveDamageReport = (id, data) => request.put(`/damageReport/${id}/approve`, data)
export const getDamageReport = (id) => request.get(`/damageReport/${id}`)

export const listLinenStocks = () => request.get('/linenStock/list')
export const updateSafetyStock = (data) => request.put('/linenStock/updateSafetyStock', data)
export const restockLinen = (data) => request.post('/linenStock/restock', data)
export const getStockByLinenType = (linenTypeId) => request.get(`/linenStock/linenType/${linenTypeId}`)
export const deductStockInUse = (data) => request.post('/linenStock/deductInUse', data)

export const listTracksByBag = (bagId) => request.get(`/linenTrack/bagId/${bagId}`)
export const listTracksByBagCode = (bagCode) => request.get(`/linenTrack/bagCode/${bagCode}`)
export const listTracksByRoom = (roomNo) => request.get(`/linenTrack/roomNo/${roomNo}`)
export const listAllTracks = () => request.get('/linenTrack/list')

export const listCostAllocation = (startDate, endDate) => request.get('/costAllocation/getByDateRange', { params: { startDate, endDate } })
export const generateDailyCost = (date) => request.post('/costAllocation/generateDaily', null, { params: { date } })
export const listAllCosts = () => request.get('/costAllocation/list')

export const listRoomRestocks = () => request.get('/roomRestock/list')
export const listRestocksByRoom = (roomId) => request.get('/roomRestock/listByRoom', { params: { roomId } })
export const listRestocksByWarehouse = (warehouseId) => request.get('/roomRestock/listByWarehouse', { params: { warehouseId } })
export const restockRoom = (data) => request.post('/roomRestock', data)
export const getRoomRestock = (id) => request.get(`/roomRestock/${id}`)
